import {
  ErButton,
  ErButtonGroup,
  ErIcon,
  ErCollapse,
  ErCollapseItem,
  ErAlert,
  ErTooltip,
  ErPopconfirm,
  ErDropdown,
  ErDropdownItem,
  ErConfigProvider,
  ErMessage,
  ErNotification,
  ErInput,
  ErMessageBox,
  ErLoading,
  ErSwitch,
  ErSelect,
  ErForm,
  ErFormItem,
} from '@learn-ui-to-me/components'
import type { Plugin } from 'vue'

export default [
  ErButton,
  ErIcon,
  ErButtonGroup,
  ErCollapse,
  ErCollapseItem,
  ErAlert,
  ErTooltip,
  ErPopconfirm,
  ErDropdown,
  ErDropdownItem,
  ErConfigProvider,
  ErMessage,
  ErNotification,
  ErInput,
  ErMessageBox,
  ErLoading,
  ErSwitch,
  ErSelect,
  ErForm,
  ErFormItem,
] as Plugin[]
